"""
yaragen.py - automatic YARA rule generator for peekaboo
extracts PE metadata, strings, and byte patterns to build a detection rule
"""
from __future__ import annotations
import hashlib
import math
import re
from datetime import datetime
from pathlib import Path

try:
    import pefile
    HAS_PEFILE = True
except ImportError:
    HAS_PEFILE = False


# -- helpers ------------------------------------------------------------------

def _entropy(data: bytes) -> float:
    if not data:
        return 0.0
    freq = [0] * 256
    for b in data:
        freq[b] += 1
    n = len(data)
    return -sum((f / n) * math.log2(f / n) for f in freq if f)


def _extract_strings(data: bytes, min_len: int = 6) -> tuple[list[str], list[bytes]]:
    """Return (ascii_strings, wide_raw_bytes)."""
    ascii_re = re.compile(rb'[\x20-\x7e]{' + str(min_len).encode() + rb',}')
    wide_re  = re.compile(rb'(?:[\x20-\x7e]\x00){' + str(min_len).encode() + rb',}')
    ascii_strs = [m.group().decode('ascii', errors='ignore') for m in ascii_re.finditer(data)]
    wide_raw   = [m.group() for m in wide_re.finditer(data)]
    return ascii_strs, wide_raw


# patterns that suggest malicious intent
_INTERESTING_RE = re.compile(
    r'cmd(?:\.exe)?|powershell|regsvr32|rundll32|mshta|wscript|cscript'
    r'|CreateRemoteThread|VirtualAlloc(?:Ex)?|WriteProcessMemory'
    r'|LoadLibrary|GetProcAddress|WinExec|ShellExecute(?:A|Ex)?'
    r'|\\Software\\Microsoft\\Windows\\CurrentVersion\\Run'
    r'|HKEY_(?:LOCAL_MACHINE|CURRENT_USER|CLASSES_ROOT)'
    r'|RegOpenKey|RegSetValue|RegCreateKey'
    r'|HttpSendRequest|InternetOpen|InternetConnect|URLDownloadToFile'
    r'|WSAStartup|WSAConnect|socket|connect|bind|listen|recv|send'
    r'|CreateProcess|OpenProcess|NtCreateThread|NtAllocateVirtualMemory'
    r'|SeDebugPrivilege|AdjustTokenPrivileges'
    r'|mimikatz|cobalt.strike|meterpreter|metasploit|beacon',
    re.IGNORECASE,
)

# strings that are too generic to be useful as indicators
_NOISE_RE = re.compile(
    r'^(?:Windows|Microsoft|Program Files|System32|kernel32|ntdll'
    r'|user32|advapi32|msvcrt|vcruntime|\.text|\.data|\.rdata'
    r'|This program|DOS mode|PE\x00\x00)$',
    re.IGNORECASE,
)


def _yara_escape(s: str) -> str:
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r')


# -- main generator ------------------------------------------------------------

def generate_rule(filepath: Path) -> dict:
    filepath = Path(filepath)
    if not filepath.exists():
        return {"ok": False, "error": f"file not found: {filepath.name}"}

    data   = filepath.read_bytes()
    md5    = hashlib.md5(data).hexdigest()
    sha256 = hashlib.sha256(data).hexdigest()
    size   = len(data)

    meta: list[str]   = []
    strings: list[str] = []
    conditions: list[str] = []

    meta.append(f'description = "Auto-generated by peekaboo for {filepath.name}"')
    meta.append(f'date        = "{datetime.now().strftime("%Y-%m-%d")}"')
    meta.append(f'author      = "peekaboo auto-yara"')
    meta.append(f'hash_md5    = "{md5}"')
    meta.append(f'hash_sha256 = "{sha256}"')
    meta.append(f'filesize_bytes = {size}')

    pe_sections = []
    pe_imphash  = ""
    needs_pe_import = False
    str_idx  = 0
    imp_vars: list[str] = []   # tracks $imp_* var names for condition

    # -- PE analysis ----------------------------------------------------------
    if HAS_PEFILE:
        try:
            pe = pefile.PE(data=data, fast_load=False)
            needs_pe_import = True

            # sections
            for sec in pe.sections:
                name = sec.Name.rstrip(b'\x00').decode('utf-8', errors='ignore')
                ent  = _entropy(sec.get_data())
                pe_sections.append({"name": name, "entropy": round(ent, 2),
                                    "size": sec.SizeOfRawData})

            high_ent = [s for s in pe_sections if s["entropy"] > 6.5]
            if high_ent:
                names = ", ".join(s["name"] for s in high_ent)
                meta.append(f'note        = "high-entropy section(s): {names} - possible packed payload"')

            # entry-point byte pattern (first 16 bytes)
            try:
                ep_rva    = pe.OPTIONAL_HEADER.AddressOfEntryPoint
                ep_offset = pe.get_offset_from_rva(ep_rva)
                ep_bytes  = data[ep_offset: ep_offset + 16]
                if ep_bytes and len(ep_bytes) == 16:
                    hex_str = ' '.join(f'{b:02x}' for b in ep_bytes)
                    strings.append(f'$ep = {{ {hex_str} }}')
                    conditions.append('$ep at pe.entry_point')
                    str_idx += 1
            except Exception:
                pass

            # imphash
            try:
                pe_imphash = pe.get_imphash()
                if pe_imphash:
                    meta.append(f'pe_imphash  = "{pe_imphash}"')
                    conditions.append(f'pe.imphash() == "{pe_imphash}"')
            except Exception:
                pass

            # section count
            n_sec = len(pe.sections)
            if n_sec:
                conditions.append(f'pe.number_of_sections == {n_sec}')

            # suspicious imports as string indicators
            if hasattr(pe, 'DIRECTORY_ENTRY_IMPORT'):
                for entry in pe.DIRECTORY_ENTRY_IMPORT:
                    for imp in entry.imports:
                        if not imp.name:
                            continue
                        name_s = imp.name.decode('utf-8', errors='ignore')
                        if _INTERESTING_RE.search(name_s) and not _NOISE_RE.match(name_s):
                            vname = f'$imp_{str_idx}'
                            strings.append(f'{vname} = "{_yara_escape(name_s)}"')
                            imp_vars.append(vname)
                            str_idx += 1
                            if str_idx > 6:
                                break
                    if str_idx > 6:
                        break

        except Exception as pe_err:
            meta.append(f'note        = "PE parse error: {str(pe_err)[:80]}"')

    # -- string extraction -----------------------------------------------------
    ascii_strs, wide_raws = _extract_strings(data)

    # pick interesting ascii strings
    interesting_ascii: list[str] = []
    seen: set[str] = set()
    for s in ascii_strs:
        if s in seen or len(s) > 120 or _NOISE_RE.match(s):
            continue
        if _INTERESTING_RE.search(s):
            interesting_ascii.append(s)
            seen.add(s)
        if len(interesting_ascii) >= 10:
            break

    # if too few hits, fall back to longest unique strings
    if len(interesting_ascii) < 4:
        for s in sorted(set(ascii_strs), key=len, reverse=True):
            if s in seen or not (8 <= len(s) <= 80) or _NOISE_RE.match(s):
                continue
            if all(0x20 <= ord(c) <= 0x7e for c in s):
                interesting_ascii.append(s)
                seen.add(s)
            if len(interesting_ascii) >= 8:
                break

    # interesting wide strings
    interesting_wide: list[str] = []
    for raw in wide_raws:
        s = raw.replace(b'\x00', b'').decode('ascii', errors='ignore')
        if s in seen or len(s) > 100 or _NOISE_RE.match(s):
            continue
        if _INTERESTING_RE.search(s):
            interesting_wide.append(s)
            seen.add(s)
        if len(interesting_wide) >= 4:
            break

    str_vars: list[str] = []
    for s in interesting_ascii[:8]:
        vname = f'$s{str_idx}'
        strings.append(f'{vname} = "{_yara_escape(s)}"')
        str_vars.append(vname)
        str_idx += 1

    for s in interesting_wide[:4]:
        vname = f'$w{str_idx}'
        strings.append(f'{vname} = "{_yara_escape(s)}" wide ascii')
        str_vars.append(vname)
        str_idx += 1

    # string condition: require at least 2 of the string indicators
    # include ALL declared $imp_*, $s*, $w* variables so none are unreferenced
    all_str_vars = imp_vars + str_vars
    if all_str_vars:
        conditions.append(f'2 of ({", ".join(all_str_vars)})')

    # filesize bounds ±25%
    lo = int(size * 0.75)
    hi = int(size * 1.25)
    conditions.append(f'filesize >= {lo} and filesize <= {hi}')

    if not conditions:
        conditions = ['true']

    # -- assemble rule ---------------------------------------------------------
    rule_name = re.sub(r'[^a-zA-Z0-9_]', '_', filepath.stem)
    if rule_name[0].isdigit():
        rule_name = 'rule_' + rule_name

    lines: list[str] = []
    if needs_pe_import:
        lines += ['import "pe"', '']
    lines += [f'rule {rule_name}', '{']
    lines.append('  meta:')
    for m in meta:
        lines.append(f'    {m}')
    if strings:
        lines.append('')
        lines.append('  strings:')
        for s in strings:
            lines.append(f'    {s}')
    lines.append('')
    lines.append('  condition:')
    # indent multi-part condition nicely
    cond = '\n    and '.join(conditions)
    lines.append(f'    {cond}')
    lines.append('}')

    rule_text = '\n'.join(lines)

    return {
        "ok":                 True,
        "rule":               rule_text,
        "rule_name":          rule_name,
        "md5":                md5,
        "sha256":             sha256,
        "size":               size,
        "string_count":       len(all_str_vars),
        "has_pe":             HAS_PEFILE and bool(pe_sections),
        "pe_sections":        pe_sections,
        "pe_imphash":         pe_imphash,
        "high_entropy_count": sum(1 for s in pe_sections if s["entropy"] > 6.5),
    }
